name: Audit live site
on: pull_request

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Audit Netlify deploy preview
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://www.wanted.co.kr'
    - uses: actions/upload-artifact@master
      with:
        name: reportMain
        path: './report'

  jd:
    runs-on: ubuntu-latest
    steps:
    - name: Audit Netlify deploy preview
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://www.wanted.co.kr/wdlist?country=kr&job_sort=job.latest_order&years=-1&locations=seoul'
    - uses: actions/upload-artifact@master
      with:
        name: reportJd
        path: './report'

  salary:
    runs-on: ubuntu-latest
    steps:
    - name: Audit Netlify deploy preview
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://www.wanted.co.kr/salary'
    - uses: actions/upload-artifact@master
      with:
        name: reportSalary
        path: './report'

  events:
    runs-on: ubuntu-latest
    steps:
    - name: Audit Netlify deploy preview
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://www.wanted.co.kr/events'
    - uses: actions/upload-artifact@master
      with:
        name: reportEvents
        path: './report'