name: Check Lighthouse
on: push

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
    - name: Create Report Wanted Main
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://www.wanted.co.kr'
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: 'report'

  job_list:
    name: job_list
    runs-on: ubuntu-latest
    steps:
    - name: Create Report Wanted Job List
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://www.wanted.co.kr/wdlist?country=kr&job_sort=job.latest_order&years=-1&locations=seoul'
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: 'report'

  job_detail:
    name: job_detail
    runs-on: ubuntu-latest
    steps:
    - name: Create Report Wanted Job Detail
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://www.wanted.co.kr/wd/32385'
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: 'report'

  salary:
    name: salary
    runs-on: ubuntu-latest
    steps:
    - name: Create Report Wanted Job Salary
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://www.wanted.co.kr/salary'
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: 'report'

  events:
    name: events
    runs-on: ubuntu-latest
    steps:
    - name: Create Report Wanted Event List
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://www.wanted.co.kr/events'
    - uses: actions/upload-artifact@master
      with:
        name: reportEvents
        path: 'report'

  event_detail:
    name: event_detail
    runs-on: ubuntu-latest
    steps:
    - name: Create Report Wanted Event Detail
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://www.wanted.co.kr/events/booktalk02'
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: 'report'

  deploy_report:
    name: deploy_report
    runs-on: ubuntu-latest
    needs: [main, job_list, job_detail, salary, events, event_detail]
    steps:
    - uses: actions/download-artifact@master
      with:
        name: report

    - name: Deploy Report to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        echo ::set-env name=DATE::$(date +%Y%m%d%H%M%S)
        
        aws s3 cp \
          --recursive \
          --region ap-northeast-2 \
          . s3://github-actions-dh/$DATE/
    