name: Audit live site
on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Create Report Wanted Main
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://www.wanted.co.kr'
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: 'report/main'

  job_list:
    runs-on: ubuntu-latest
    steps:
    - name: Create Report Wanted Job List
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://www.wanted.co.kr/wdlist?country=kr&job_sort=job.latest_order&years=-1&locations=seoul'
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: 'report/jl'

  job_detail:
    runs-on: ubuntu-latest
    steps:
    - name: Create Report Wanted Job Detail
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://www.wanted.co.kr/wd/32385'
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: 'report/jd'

  salary:
    runs-on: ubuntu-latest
    steps:
    - name: Create Report Wanted Job Salary
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://www.wanted.co.kr/salary'
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: 'report/salary'

  events:
    runs-on: ubuntu-latest
    steps:
    - name: Create Report Wanted Event List
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://www.wanted.co.kr/events'
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: 'report/event'

  event_detail:
    runs-on: ubuntu-latest
    steps:
    - name: Create Report Wanted Event Detail
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://www.wanted.co.kr/events/booktalk02'
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: 'report/ed'

  deploy_report:
    runs-on: ubuntu-latest
    needs: [main, job_list, job_detail, salary, events, event_detail]
    steps:
    - uses: actions/download-artifact@master
      with:
        name: report